/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[17] = {16, 1, 0, 13, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* mav_nmpc_tracker_model_expl_vde_adj:(i0[12],i1[12],i2[4],i3[])->(o0[16x1,13nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 12, w0);
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  w5 = w0[4];
  w6 = w0[5];
  w7 = w0[6];
  w8 = w0[7];
  w9 = w0[8];
  w10 = w0[9];
  w11 = w0[10];
  w12 = w0[11];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #5: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #6: @2 = cos(@3) */
  w2 = cos( w3 );
  /* #7: @1 = input[0][8] */
  w1 = arg[0] ? arg[0][8] : 0;
  /* #8: @13 = cos(@1) */
  w13 = cos( w1 );
  /* #9: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #10: @15 = cos(@14) */
  w15 = cos( w14 );
  /* #11: @16 = (@13*@15) */
  w16  = (w13*w15);
  /* #12: @17 = input[2][0] */
  w17 = arg[2] ? arg[2][0] : 0;
  /* #13: @18 = (@17*@5) */
  w18  = (w17*w5);
  /* #14: @19 = (@16*@18) */
  w19  = (w16*w18);
  /* #15: @2 = (@2*@19) */
  w2 *= w19;
  /* #16: @2 = (-@2) */
  w2 = (- w2 );
  /* #17: @19 = sin(@3) */
  w19 = sin( w3 );
  /* #18: @20 = cos(@14) */
  w20 = cos( w14 );
  /* #19: @21 = (@17*@6) */
  w21  = (w17*w6);
  /* #20: @22 = (@20*@21) */
  w22  = (w20*w21);
  /* #21: @19 = (@19*@22) */
  w19 *= w22;
  /* #22: @2 = (@2-@19) */
  w2 -= w19;
  /* #23: @19 = cos(@3) */
  w19 = cos( w3 );
  /* #24: @22 = cos(@14) */
  w22 = cos( w14 );
  /* #25: @23 = sin(@1) */
  w23 = sin( w1 );
  /* #26: @17 = (@17*@4) */
  w17 *= w4;
  /* #27: @24 = (@23*@17) */
  w24  = (w23*w17);
  /* #28: @25 = (@22*@24) */
  w25  = (w22*w24);
  /* #29: @19 = (@19*@25) */
  w19 *= w25;
  /* #30: @2 = (@2+@19) */
  w2 += w19;
  /* #31: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #32: @2 = sin(@14) */
  w2 = sin( w14 );
  /* #33: @19 = sin(@3) */
  w19 = sin( w3 );
  /* #34: @25 = (@19*@18) */
  w25  = (w19*w18);
  /* #35: @13 = (@13*@25) */
  w13 *= w25;
  /* #36: @2 = (@2*@13) */
  w2 *= w13;
  /* #37: @13 = sin(@14) */
  w13 = sin( w14 );
  /* #38: @26 = cos(@3) */
  w26 = cos( w3 );
  /* #39: @21 = (@26*@21) */
  w21  = (w26*w21);
  /* #40: @13 = (@13*@21) */
  w13 *= w21;
  /* #41: @2 = (@2-@13) */
  w2 -= w13;
  /* #42: @13 = cos(@14) */
  w13 = cos( w14 );
  /* #43: @21 = sin(@1) */
  w21 = sin( w1 );
  /* #44: @27 = (@21*@18) */
  w27  = (w21*w18);
  /* #45: @13 = (@13*@27) */
  w13 *= w27;
  /* #46: @2 = (@2+@13) */
  w2 += w13;
  /* #47: @13 = sin(@14) */
  w13 = sin( w14 );
  /* #48: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #49: @24 = (@3*@24) */
  w24  = (w3*w24);
  /* #50: @13 = (@13*@24) */
  w13 *= w24;
  /* #51: @2 = (@2-@13) */
  w2 -= w13;
  /* #52: @13 = cos(@14) */
  w13 = cos( w14 );
  /* #53: @24 = cos(@1) */
  w24 = cos( w1 );
  /* #54: @27 = (@24*@17) */
  w27  = (w24*w17);
  /* #55: @13 = (@13*@27) */
  w13 *= w27;
  /* #56: @2 = (@2+@13) */
  w2 += w13;
  /* #57: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #58: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #59: @15 = (@15*@25) */
  w15 *= w25;
  /* #60: @2 = (@2*@15) */
  w2 *= w15;
  /* #61: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #62: @25 = sin(@14) */
  w25 = sin( w14 );
  /* #63: @18 = (@25*@18) */
  w18  = (w25*w18);
  /* #64: @15 = (@15*@18) */
  w15 *= w18;
  /* #65: @2 = (@2+@15) */
  w2 += w15;
  /* #66: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #67: @22 = (@22*@3) */
  w22 *= w3;
  /* #68: @3 = (@22*@17) */
  w3  = (w22*w17);
  /* #69: @15 = (@15*@3) */
  w15 *= w3;
  /* #70: @2 = (@2+@15) */
  w2 += w15;
  /* #71: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #72: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #73: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #74: @1 = (@1*@17) */
  w1 *= w17;
  /* #75: @2 = (@2-@1) */
  w2 -= w1;
  /* #76: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #77: @2 = -1.46e-05 */
  w2 = -1.4600000000000001e-05;
  /* #78: @1 = input[0][11] */
  w1 = arg[0] ? arg[0][11] : 0;
  /* #79: @17 = 69930.1 */
  w17 = 6.9930069930069934e+04;
  /* #80: @17 = (@17*@11) */
  w17 *= w11;
  /* #81: @15 = (@1*@17) */
  w15  = (w1*w17);
  /* #82: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #83: @15 = (@15+@7) */
  w15 += w7;
  /* #84: output[0][6] = @15 */
  if (res[0]) res[0][6] = w15;
  /* #85: @15 = 1.46e-05 */
  w15 = 1.4600000000000001e-05;
  /* #86: @7 = 69930.1 */
  w7 = 6.9930069930069934e+04;
  /* #87: @7 = (@7*@10) */
  w7 *= w10;
  /* #88: @1 = (@1*@7) */
  w1 *= w7;
  /* #89: @1 = (@15*@1) */
  w1  = (w15*w1);
  /* #90: @1 = (@1+@8) */
  w1 += w8;
  /* #91: output[0][7] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #92: @1 = input[0][9] */
  w1 = arg[0] ? arg[0][9] : 0;
  /* #93: @2 = (@2*@1) */
  w2 *= w1;
  /* #94: @2 = (@2*@17) */
  w2 *= w17;
  /* #95: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #96: @15 = (@15*@17) */
  w15 *= w17;
  /* #97: @15 = (@15*@7) */
  w15 *= w7;
  /* #98: @2 = (@2+@15) */
  w2 += w15;
  /* #99: @2 = (@2+@9) */
  w2 += w9;
  /* #100: output[0][8] = @2 */
  if (res[0]) res[0][8] = w2;
  /* #101: @20 = (@20*@26) */
  w20 *= w26;
  /* #102: @20 = (@20*@6) */
  w20 *= w6;
  /* #103: @21 = (@21*@25) */
  w21 *= w25;
  /* #104: @16 = (@16*@19) */
  w16 *= w19;
  /* #105: @21 = (@21-@16) */
  w21 -= w16;
  /* #106: @21 = (@21*@5) */
  w21 *= w5;
  /* #107: @20 = (@20+@21) */
  w20 += w21;
  /* #108: @24 = (@24*@14) */
  w24 *= w14;
  /* #109: @22 = (@22*@23) */
  w22 *= w23;
  /* #110: @24 = (@24+@22) */
  w24 += w22;
  /* #111: @24 = (@24*@4) */
  w24 *= w4;
  /* #112: @20 = (@20+@24) */
  w20 += w24;
  /* #113: output[0][9] = @20 */
  if (res[0]) res[0][9] = w20;
  /* #114: @20 = 69930.1 */
  w20 = 6.9930069930069934e+04;
  /* #115: @20 = (@20*@10) */
  w20 *= w10;
  /* #116: output[0][10] = @20 */
  if (res[0]) res[0][10] = w20;
  /* #117: @20 = 69930.1 */
  w20 = 6.9930069930069934e+04;
  /* #118: @20 = (@20*@11) */
  w20 *= w11;
  /* #119: output[0][11] = @20 */
  if (res[0]) res[0][11] = w20;
  /* #120: @20 = 34602.1 */
  w20 = 3.4602076124567473e+04;
  /* #121: @20 = (@20*@12) */
  w20 *= w12;
  /* #122: output[0][12] = @20 */
  if (res[0]) res[0][12] = w20;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
